### ISSUE TITLE
DISCUSSION: auto creation of a schema?

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1022]
The idea is born based on the input of two responses I received (thanks @pa3bmg ;-) )

### Concept

What if we would have the ability to create a schema automatically? That one can have a boolean option when running Weaviate (auto-schema, yes, no?).

- **no** = as is.
- **yes** = when a user creates a new thing or action via the RESTful endpoint, Weaviate determines if the schema exists, if not, it attempts to create it.

I would even suggest running with `true` as a standard.

### Why?

An end-user can add things and actions without creating a schema first.

### Downsides?

If somebody adds a property with an `int` first and later adds a `float` / `number` Weaviate would try to fit in with the existing schema.

### Suggestion for inner workings

I would suggest making it rely on Weaviate 100% (not ES).

#### Flow # 1 - new class

0. The user creates a new thing or action with a new class.
0. Weaviate determines the types of the schema properties.
0. Weaviate attempts to create the class.
0. Weaviate attempts to add the data.

#### Flow # 2 - exsisting class, new properties

0. The user creates a new thing or action with an existing class.
0. Weaviate detects a new property.
0. Weaviate attempts to create the new property.
0. Weaviate attempts to add the data.

#### Flow # 3 - nested class

0. The user creates a new thing or action with a nested class.
0. Weaviate follows # 1 or # 2 and creates the new nested classes.

Example:

```yaml
Company:
  name: Apple
  foundedIn: 1976
  inCountry:
    "$cref": ...
  hasCeo: # <== indicates a nested schema item
    Person: # <== determines flow # 1 or # 2
      name: Tim Cook
```

### Participants

cc:
- @fefi42 
- @laura-ham 
- @etiennedi 
- @pa3bmg
