### ISSUE TITLE
DISCUSSION: add basic graph algorithms

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate#1023]
_Based on feedback from @pa3bmg_

The idea is to have basic graph algos available through the GQL API.

For example:
- https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm

cc:
- @fefi42 
- @laura-ham 
- @etiennedi 
- @pa3bmg

**Comment by etiennedi** [comment]
## Technical Background

Something like Dijkstra should not be an issue. For anything that is within the `denormalizationLimit` this can be instant. For really long paths, a few follow-up requests will be necessary, but this should still be within the realm of real-time.

We can essentially split this problem up into two parts, since we have the schema. I.e. if we want to get from `Person: Tim Cook` to `Country: Canada`, we can calculate all possible schema ways to get there. For example:

1. Person -> livesIn -> Country 
2. Person -> livesIn -> Country -> sharesBorderWith -> Country
3. Person -> isCEO -> Company -> doesBusinessWith -> Country
4. Person -> isCEO -> Company -> isLocatedin -> Country -> sharesBorderWith -> Country
etc.

Then we can limit the amount of possible objects to take into account with the Dijkstra algorithm

## API

Any suggestions for what an API would look like? 

I could imagine something (I'm keeping this agnostic of any tech like GQL or REST for now on purpose)

### Input: 

```yaml
source:
  class: Person
  id: 12345
target: 
  class: Person
  id: 54321
```

### Output

```yaml
hops: 3
semanticalDistance: 0.7
objects: # in beacon format
  - weaviate://localhost/things/12345 # always starts with source
  - weaviate://localhost/things/09892 
  - weaviate://localhost/things/23423 
  - weaviate://localhost/things/54321 # always ends with target
```

This is far from perfect, but meant as a base to start discussion.

**Comment by bobvanluijt** [comment]
# Shortest path

Cool, thinking of taking this one step further.

Maybe we can also (as in, additionally) create a semantic shortest path?

```yaml
source:
  class: Person
  id: 12345
target: 
  concepts:
    - Capital
```

⬆️ just an idea... 😄 

PS:
I believe it would be good to try to aim for GQL.

# Others?

Any other ones we need? Any suggestions @pa3bmg?
