### ISSUE TITLE
influence weighting in contextual classification

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate#1070]
If the classification is executed using fields with a small number of words (1-3) then the weight of single words can throw off the classification by a lot. While one word might be way more significant in a big corpus this does not have to be true for a small corpus. 

It would be nice if the weights applied to the classification could be influenced. To set them either uniformaly to the same value or to boost or throttle specific terms. 

E.g. matching different meta fields:
```
{
  dataType: "string"
  variableName: "license plate"
}
```
We might want to throttle string since it is important but not too much so and boost plate since it might get matched with the wrong license otherwise.

**Comment by etiennedi** [comment]
# Suggested interface

For both example assume the original weights are:

```yaml
string: 0.7
license: 0.5
plate: 0.2
```

In both examples, the object itself (not the schema class) would be extended with the proposed fields

## Alternative 1 "Boosting"
Boosting would respect the original weight and multiply it with the boost.

Example:
```yaml
vectorizationBoosts:
  string: 0.5
  plate: 5
```

would lead to final weights of 
```yaml
string: 0.35 # halved through boosting
license: 0.5 # not affecting from boosting
plate: 1.0 # boosted by factor of 5
```

## Alternative 2 "Replacing Weights"
Replacing would ignore what the original weight (based on occurrence) was and would instead replace the weight altogether

Example:
```yaml
vectorizationWeights:
  string: 0.3
  plate: 1
```

would lead to final weights of 
```yaml
string: 0.3 # replaced to absolute value
license: 0.5 # not affecting from replacing
plate: 1.0 # replaced to absolute value
```

@bobvanluijt, @laura-ham, @fefi42 Which one do you like better? Do you like them at all? Any other ideas, proposals, concerns?

Small comment on the side, the title mentions "in contextual classification". Since the contextual classification just uses the objects vector we can't isolate the effect only to the classification. We'd influence the object position for all use cases (also search etc.). I don't think that's an issue, just wanted to make this explicitly clear.

**Comment by bobvanluijt** [comment]
I would be inclined to go with boosting because it might be confusing for the user to understand what the actual position is. Boosting is also something one can "play around with" more easily.

Something else, how about boosting in percentages? 

```
vectorizationBoosts:
  string: 1.5 <== 150%
```

**Comment by fefi42** [comment]
Boosting could also be counter intuitive since the words do not start out from the same base.
if we have something like:
``` json
string: 0.01
license: 0.5
```
Then people might start boosting `string: 3.0` but they still don't see any change while with other words they might dominate the whole corpus.

**Comment by etiennedi** [comment]
> Something else, how about boosting in percentages?

What would the data type of the field then be? `string` and then the user explicitly sets a `%` sign at the end? Or `float` but the value is divided by 100? I find neither as intuitive as a simple multiplier.

> Boosting could also be counter intuitive since the words do not start out from the same base.

That was also my reasoning behind Alternative 2. Boosting is more difficult if you don't know the base value you're boosting. What if we allow both alternatives, but the user can only set one? I.e. they could go with boosting if all they care about boosting or penalizing a single field, or they could go with replacements if they need ultimate control over a vector's weights?

**Comment by fefi42** [comment]
I am against percentages and I tend more towards absolute overwrites.

**Comment by bobvanluijt** [comment]
Another idea, what if you would do it algebraically. For example, where `x` is the current value.

- `license: "x"` <== license keeps the same weight.
- `license: "x + 1"` <== license keeps the weight + 1.
- `license: "x * 1.5"` <== license 150% of the original weight.
- `license: "2"` <== license is set to 2.
- etcetera.

PS:
Potentially makes it to complex.

**Comment by etiennedi** [comment]
I think the proposal to parse simple equations is a great one, but it will also increase the implementation cost quite a bit. Maybe we could go for the format, but only allow a single one, e.g. `x * 1.5` at first and gradually add the other ones later as we need them?

**Comment by fefi42** [comment]
That would be ok for me. I would then vote for `x + 1.5` as the first available option.

**Comment by etiennedi** [comment]
I think we still need to agree on what we call the above in the API. Since it can now be both replace and boost, I think a very neutral `vectorWeights` might do the trick. So here's an example for a full thing object:

`POST /v1/things/`
```yaml
Class: CarPart
schema:
  partName: "license plate holder"
vectorWeights:
  license: "12 * w - 48.22" # with w being the original weight
  plate: "7"
```

In case it's not obvious, in the above we would:
- for `license` take 12 times the original weight, then substract 48.22
- for `plate` regardless of the original weight always use 7
- for `holder` nothing is changed, would be exactly as before

- Everyone happy with the API? 
- Everyone happy with `vectorWeights`? Alternative Ideas?

**Comment by fefi42** [comment]
I am happy with this. For completeness would a later post with:
```yaml
Class: CarPart
schema:
  partName: "license plate holder"
vectorWeights:
  license: "w"
  plate: "w"
```
reset the weights to the original value or will it keep the weights set before?
