### ISSUE TITLE
API Discussion: New Type "phoneNumber"

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1087]
## Background
As part of the investigations of #1081 and #1086 we have learnt that the highest value at the moment is in normalizing and validating phone numbers as opposed to addresses.

## Goals
The following cases should work
1. The user enters the same phone number twice in different formats, e.g. `+49 (0) 234 456789` and `+49234456789`. When stored, those should be identical
2. The user enters the number in a non-international format, e.g. `0234 456789`, it should be stored in an international format

## API proposal
- A new `dataType` is introduced: `phoneNumber`
- `phoneNumber` is an object (as opposed to a flat type similar to `geoCoordinates`)
- `phoneNumber` has the following structure:
  ```yaml
  phoneNumber:
    input: "0171 12345678"
    defaultCountry: "de"
    internationalFormatted: "+49 171 12345678"
    countryCode: 49
    national: 17112345678
    nationalFormatted: "0171 12345678"
    valid: true
  ```
- When creating a new number the user has to either fill **one or two of the fields** depending on the following: 
  - only `input` when the number is in an international format
  - both `input` and `defaultCountry` when the number is in a national format
- When the user doesn't know if the number is in national or international format, the safe option is to fill both fields, as `defaultCountry` will be ignored, if the number is an international number.

## Notes
- The available fields and their names are modelled after [nyaruka/phonenumbers](https://github.com/nyaruka/phonenumbers) which is a go port of Google's [libphonenumber](https://github.com/google/libphonenumber).
- If we decide we do not need all fields, we can also remove them as long as we keep the fields we need for the parsing to function.

## Discussion points
1. Are we happy with the format above?
2. How do we search for numbers? In the where filter we could introduce `valuePhoneNumber` or possibly `valuePhoneNumberInternational` if we want to be more precise. Ideas?

cc @bobvanluijt  @fefi42 @laura-ham @michaverhagen
