### ISSUE TITLE
First installation issues with docker

### ISSUE THREAD

**Issue by WolfgangFahl** [semi-technologies/weaviate#1215]
Trying to follow https://www.semi.technology/documentation/weaviate/current/get-started/install.html#docker-compose

i created a script 'installweaviate':
```
# Weaviate with an English Contextionary
# Download the Weaviate configuration file
curl -O https://raw.githubusercontent.com/semi-technologies/weaviate/0.22.14/docker-compose/runtime/en/config.yaml
# Download the Weaviate docker-compose file
curl -O https://raw.githubusercontent.com/semi-technologies/weaviate/0.22.14/docker-compose/runtime/en/docker-compose.yml
# Run Docker Compose
docker-compose up
```
When i ran in on my Mac OS / macports laptop it started fine using docker desktop 2.3.03 with compose 1.25.5.
When i saw that the procedure tried downloading 6 GBytes i had to stop things since my disk is almost full on the laptop. 

I moved to my Ubuntu server with a 10 TB disk and started the script there.
`ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
`

I find this quite frustrating since i can not immediately overcome these two hurdles. It would be good if the documentation would state:
- what OS, docker, composer, ... is needed
- how much diskspace is needed

and how to work around these issues if the enviroment does not fullfill these prerequisites.

**Comment by WolfgangFahl** [comment]
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

docker-compose --version
docker-compose version 1.15.0, build e12f3b9
which docker-compose
/usr/local/bin/docker-compose
```

**Comment by WolfgangFahl** [comment]
Have to check e.g.  https://phoenixnap.com/kb/install-docker-compose-ubuntu how to update docker-compose (seems not be part of the packages supplied by ubuntu ....)

**Comment by WolfgangFahl** [comment]
https://docs.docker.com/compose/compose-file/
typical version hell waiting to burn you ...

**Comment by etiennedi** [comment]
@WolfgangFahl Thanks for creating this issue. Did you get it to run eventually?

We are using the docker-compose file version `3.4` which according to the Docker docs requires at least [Docker Engine version 17.09.0](https://docs.docker.com/compose/compose-file/compose-versioning/#version-34). it sees that you have a newer version that that (`18.09.01`). So that shouldn't be the issue.

Unfortunately I can't find anything in the Docker docs about which `docker-compose` binary version is required. I'm using `docker-compose version 1.25.2, build 698e2846` so it seems the requirement is somewhere between `1.15` and `1.25`.

**Comment by WolfgangFahl** [comment]
I tried on a MacOS machine with more disk space and the instance seems to be up on port 8080.
On a virtual machine with debian buster I am stuck after:
`sudo apt-get install curl docker docker-compose`

```
docker --version
Docker version 18.09.1, build 4c52b90
wf@confident23:/usr/local/src/weaviate$ docker-compose --version
docker-compose version 1.21.0, build unknown
```
`./installweaviate 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   323  100   323    0     0   8282      0 --:--:-- --:--:-- --:--:--  8282
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1357  100  1357    0     0  45233      0 --:--:-- --:--:-- --:--:-- 45233
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
`

I couldn't find any hint on how to go from there since the docker documenation assumes that docker would be installed as docker-ce and there is also an assumption the dockerd command would be available. Both seem not to hold true in this environment.

**Comment by etiennedi** [comment]
> I couldn't find any hint on how to go from there since the docker documentation assumes that docker would be installed as docker-ce and there is also an assumption the dockerd command would be available. Both seem not to hold true in this environment.

If I remember correctly by default the user used to install docker is not added to the docker group on Linux, so this could be a permissions issue. Could you try if `sudo docker-compose up` works? If yes, you can add your user to the Docker group [as outline here](https://docs.docker.com/engine/install/linux-postinstall/).

**Comment by WolfgangFahl** [comment]
The debian environment might be fine if i could get the docker daemon to run from the command line with out installing things as a service. I am only interested in a quick trial and not a full-fledged installation. That's what docker's original promise was but since 2015 more often than not when trying docker things will not work out of the box - docker has IMHO failed it's original promise badly (just like Java - 'compile once run everwhere ...'). Downstream solutions like weaviate have to suffer from this - for widespread adoption things should be much simpler - e.g. it might be worthwhile to avoid docker-compose and put a solution into the docker repository for direct use after testing it in Mac OS debian, ubuntu, Windows and so  on ...

**Comment by WolfgangFahl** [comment]
on debian:
`sudo docker-compose up
Creating network "weaviate_default" with the default driver
Pulling contextionary (semitechnologies/contextionary:en0.16.0-v0.4.15)...
en0.16.0-v0.4.15: Pulling from semitechnologies/contextionary
df20fa9351a1: Pull complete
`
works fine ...

**Comment by WolfgangFahl** [comment]
Please deinstall the stalebot it will not solve issues but lead to extra effort - issues don't go away just because time passes by.

**Comment by etiennedi** [comment]
Hi @WolfgangFahl,

the stalebot is a tool that helps us prioritize. It sends a gentle reminder to the participants that an issue has been stale for 60 days 1 week before it is about to close the issue. However, it will only close if there is no further activity. It's not meant to hide issues, but with a very small team we can only focus on a certain amount of issues in a given time frame. If we and the community open 100 issues a month, but we have the capacity to work on 10, there is no more point in a ticketing system after a short while. If we have to close issues, I'd rather close stale ones than very active ones. By the way, a closed issue is not deleted, it's still there, just no longer active. It can also be reopened at any time.

All you have you to do keep your issue open for another 60 days, is leave a comment they way you did. I think that's a very small price to pay in exchange for completely free software and free support. Given that open-source works in both direction, every issue author is also free to submit a fix for whatever issue they encounter themselves. This way issue authors aren't bound by our prioritization and can give something back. 

Having said all of the above, isn't closing this issue correct? From what I understand the original issue has been solved and the docker-compose setup is usable for you? I can't distill a clear action item from this issue that would justify leaving it open. Please do correct me if it is there and I'm missing it.

We have no interested in "hiding" issues, but we need to keep active issues to a minimum if we don't want development to stall altogether.

Best
Etienne

**Comment by WolfgangFahl** [comment]
projects like docker work this way and there are major issues that are open after years.

Personally i feel the most important items for an issue are Assignee, Label and Milestone. 
For this issue to be closed the part

_It would be good if the documentation would state:

    what OS, docker, composer, ... is needed
    how much diskspace is needed

and how to work around these issues if the enviroment does not fullfill these prerequisites._

is the most relevant for me since I didn't try to install weaviate again yet on one of the target virtual machines with low RAM and diskspace not knowing what would happen.

**Comment by etiennedi** [comment]
> It would be good if the documentation would state:

Thanks, I've created an issue regarding this on our internal issue tracker for the website. Leaving open here in the meantime.

**Comment by WolfgangFahl** [comment]
I still can't install weaviate. I am trying to  follow https://weaviate.io/developers/weaviate/installation and there are several "variables" which need to be set. 

1. the image name - i choose "weaviate"
2. the port for the contextionary - i can't use 9999 since that is already used by blazegraph - i am trying to use 9990
3. the url EXTENSIONS_STORAGE_ORIGIN 

I have a hard time understanding the docker-compose.yml file since it's using non-standard url syntax the yaml file below does not work:
```yaml
version: '3.4'
services:
  weaviate:
    image: weaviate 
    ports:
      - 8080:8080
    environment:
      CONTEXTIONARY_URL: contextionary:9990
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './data'
      ENABLE_MODULES: 'text2vec-contextionary'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      AUTOSCHEMA_ENABLED: 'false'
  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://localhost:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-v1.2.1
``` 

i get
```
weaviate-weaviate-1       | {"action":"startup_check_contextionary","error":"rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.28.0.16:9990: connect: connection refused\"","level":"warning","msg":"could not connect to contextionary at startup, trying again in 1 sec","time":"2023-06-10T09:25:54Z"}
```

**Comment by WolfgangFahl** [comment]
I am now using a generated yaml file:
```yaml
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.19.6
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      OPENAI_APIKEY: ***not shown***
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,generative-openai'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
...
```

**Comment by WolfgangFahl** [comment]
Still no progress and no reopen?

**Comment by trengrj** [comment]
Hi @WolfgangFahl , I see you are hit previously some disk limits using the transformers module so it makes more sense to use the OpenAI vectorizer module considering you are already using OpenAI. This config would work.

```
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.19.9
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      OPENAI_APIKEY: ***not shown***
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai,generative-openai'
      CLUSTER_HOSTNAME: 'node1'
...
```

You can see here without the transformers container (which needs significant storage for pytorch dependencies and the model itself) the storage requirements of Weaviate are quite low.

```
docker ps --size
CONTAINER ID   IMAGE                              COMMAND                  CREATED         STATUS        PORTS                    NAMES                SIZE
66340ec1f978   semitechnologies/weaviate:1.19.9   "/bin/weaviate --hos…"   3 seconds ago   Up 1 second   0.0.0.0:8080->8080/tcp   testing-weaviate-1   81.9kB (virtual 46.8MB)
```
