### ISSUE TITLE
port configuration during setup

### ISSUE THREAD

**Issue by WolfgangFahl** [semi-technologies/weaviate#1681]
https://www.semi.technology/developers/weaviate/current/getting-started/installation.html has quite few choices. Unfortunately the choice of the port for the service is currently not possible. My Jenkins Continuous Integration for e.g. https://github.com/WolfgangFahl/pyWeaviateTest currently fails since port 8080 is in use by jenkins itself.

**Comment by etiennedi** [comment]
Given the complexity that the configurator already has (#1680), I'm hesitant to add yet another question. Maybe we could add a link to a page on how to further customize the file further, so that users could manually edit the file to change the port? There are also a few environment variable settings that aren't included in the generator, but the idea is that if someone wants to go this deep, it's ok to manually edit the files. (cc @laura-ham)

**Comment by WolfgangFahl** [comment]
IMHO it's just one more field in a dialog:
![grafik](https://user-images.githubusercontent.com/1336221/133972451-f333d342-3162-459b-9009-009698531051.png)
see http://diagrams.bitplan.com/render/png/0x4e49a1f0.png
source text at http://diagrams.bitplan.com/render/txt/0x4e49a1f0.txt
editable at https://diagrams.bitplan.com using "plantuml" for rendering

**Comment by WolfgangFahl** [comment]
What's more is that there should be an option for the configurator's REST API so that no special handling is necessary. Currently i am tentatively thinking about adding code for getting and setting the port in the .yml file for the automatic CI handling in my own python project. It seems awkward to have to do this.

**Comment by etiennedi** [comment]
Are you retrieving the configurations dynamically on CI? Please note that there are no stability guarantees on that API. It's single purpose is to serve the UI on our website. For example, if a new field is added in the future and it is not set in old links, they will break.

If we added named configs / preset as outlined in #1680, we could guarantee that those are stable, but current links are not.

**Comment by WolfgangFahl** [comment]
Currently i have no other option than to try to keep up to date with the changes semi technologies makes to the configuration process and the versions of the docker core products and the python library. I have not been able to integrate weaviate into any of my projects yet due to this "moving target" nature. Any time i find a few hours to work on things the hours are eaten up by getting up-to-date with the changes in configuration and versions. E.g. lately i had to do a 1 hour download three times failing due to limited docker space before i could continue. That's why added #1682 which points to the issue of the size of downloads necessary which makes local installations awkward for the time needed for download if there is no high-speed internet connection available.

**Comment by WolfgangFahl** [comment]
I still can't test weaviate in my CI since i don't even know how to run weaviate on a different port than 8080. How could i change the .yml file to get this effect? There are four 8080 references at this time in the setup i am using:
```yaml
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.7.0
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
...
```
