### ISSUE TITLE
Aggregation on array data type?

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1686]
Hi,

Is it possible to aggregate on array data type?

The Query:
```
{
  Get {
    Weaviate {
      categories
    }
  }
  Aggregate {
    Weaviate(groupBy: ["categories"]) {
      meta {
        count
      }
      groupedBy {
        value
      }
    }
  }
}
```

The result:
`{
  "data": {
    "Aggregate": {
      "Weaviate": null
    },
    "Get": {
      "Weaviate": [
        {
          "categories": null
        },
        {
          "categories": null
        },
        {
          "categories": null
        },
        {
          "categories": [
            "category with () ' \"\" &amp; @",
            "Uncategorized"
          ]
        }
      ]
    }
  },
  "errors": [
    {
      "locations": [
        {
          "column": 5,
          "line": 11
        }
      ],
      "message": "runtime error: hash of unhashable type []string",
      "path": [
        "Aggregate",
        "Weaviate"
      ]
    }
  ]
}`

**Comment by etiennedi** [comment]
Thanks for raising this, this should definitely be possible, so it's very likely a bug. We'll look into it.

**Comment by eostis** [comment]
@etiennedi How can I use the new version with array aggregation??

**Comment by etiennedi** [comment]
A new release will most likely be published within the next 24h. If you want to use it before the official release you can build your own container off the master `branch` using:

```
docker build --target weaviate -t name-of-your-weaviate-image .
```

And replace the weaviate image in your docker-compose.yml accordingly

**Comment by eostis** [comment]
Perfect.

The full procedure (could be added to https://www.semi.technology/developers/weaviate/current/getting-started/installation.html)

```
git clone https://github.com/semi-technologies/weaviate.git
cd weaviate
docker build --target weaviate -t weaviate-branch-master .

```

```
version: '3.4'
services:
  weaviate:
    image: weaviate-branch-master
    ports:
      - 8765:8080
    environment:
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: './data'
      ENABLE_MODULES: 'text2vec-contextionary'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      AUTOSCHEMA_ENABLED: 'false' # Important to add custom WPSOLR data types
  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-v1.0.2

```
