### ISSUE TITLE
Relative PERSISTENCE_DATA_PATH does not appear to work

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1694]
My docker file:
```
version: '3.4'
services:
  weaviate:
    image: weaviate-branch-master
    ports:
      - 8765:8080
    environment:

      PERSISTENCE_DATA_PATH: './data'
  
    CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      ENABLE_MODULES: 'text2vec-contextionary'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-contextionary'
      AUTOSCHEMA_ENABLED: 'false' # Important to add custom WPSOLR data types
  contextionary:
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
    image: semitechnologies/contextionary:en0.16.0-v1.0.2
```

After starting weaviate, there is no data created in the local docker file's folder.

**Comment by etiennedi** [comment]
The path `./data` you created is relative to the containers file system which is not persistent by default. To map it to a local folder on your disk you need to mount a [Docker Volume](https://docs.docker.com/storage/volumes/).

For example:
```
services:
  weaviate:
    image: weaviate-branch-master
    environment:
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
    volumes:
     - '/path/on/your/machine:/var/lib/weaviate'
```
