### ISSUE TITLE
Apply Q&A to all answers, not just the first

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#1791]
I'm trying to retrieve all the colors of a specific WooCommerce product (dog leash) with Q&A suggestions (which is incredible and impossible to do with a standard search !!!).
 
As featured below, the _additional property is empty after the first answer.
I tried many queries.

WooCommerce products:

![image](https://user-images.githubusercontent.com/1785759/150173763-863646a3-57c3-4aab-8319-1cd77cc176da.png)

WooCommerce Q&A suggestion:

![image](https://user-images.githubusercontent.com/1785759/150174127-4918ccfc-901a-403e-b177-91ed9eb3ddb6.png)

GraphQL query and response:

```
{
  search: Get {
    WeaviateWooCommerce(
      ask: {question: "what color are the leashes ?", properties: ["wpsolr_title", "wpsolr_content"]}
      limit: 2
    ) {
      wpsolr_title
      wpsolr_content
      _additional {
        answer {
          hasAnswer
          certainty
          property
          result
          startPosition
          endPosition
        }
      }
    }
  }
}

```

```
{
  "data": {
    "search": {
      "WeaviateWooCommerce": [
        {
          "_additional": {
            "answer": {
              "certainty": 0.7445623397827148,
              "endPosition": 4,
              "hasAnswer": true,
              "property": "wpsolr_title",
              "result": "pink",
              "startPosition": 0
            }
          },
          "wpsolr_content": "A  pink leash for dogs",
          "wpsolr_title": "Pink dog leash"
        },
        {
          "_additional": {
            "answer": null
          },
          "wpsolr_content": "A  green leash for dogs",
          "wpsolr_title": "Green dog leash"
        }
      ]
    }
  }
}
```

Docker compose file:

```
version: '3.4'
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.9.0
    ports:
      - 8766:8080
    volumes:
      - './docker_volumes/weaviate:/var/lib/weaviate'
    restart: on-failure:0
    environment:
      AUTOSCHEMA_ENABLED: 'false' # Important to add custom WPSOLR data types
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'

      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QNA_INFERENCE_API: 'http://qna-transformers:8080'
      IMAGE_INFERENCE_API: 'http://i2v-neural:8080'
      NER_INFERENCE_API: 'http://ner-transformers:8080'
      SPELLCHECK_INFERENCE_API: 'http://text-spellcheck:8080'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,qna-transformers,ner-transformers,text-spellcheck,img2vec-neural'
      CLUSTER_HOSTNAME: 'node1'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
  qna-transformers:
    image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
    environment:
      ENABLE_CUDA: '0'
  ner-transformers:
    image: semitechnologies/ner-transformers:dbmdz-bert-large-cased-finetuned-conll03-english
    environment:
      ENABLE_CUDA: '0'
  text-spellcheck:
    image: semitechnologies/text-spellcheck-model:pyspellchecker-en
  i2v-neural:
    image: semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'

```
