### ISSUE TITLE
Extend t2v-transformers module with dense passage retrieval Dual Encoding 

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#1828]
At the moment the `text2vec-transformers` module only supports **single encoding**. This means the same trained model is used for passage/text encoding as well as question/query encoding. The suggestion is to extend this module to support **dual encoding**: using a separate model for passage encoding vs. query encoding. (easy explanation of how Dense Passage Retrieval (DPR) with dual encoding works: https://towardsdatascience.com/how-to-create-an-answer-from-a-question-with-dpr-d76e29cc5d60).

A proposal for extending the `text2vec-transformers` module is the following:
* We introduce the environment variables `TRANSFORMERS_PASSAGE_INFERENCE_API` and `TRANSFORMERS_QUERY_INFERENCE_API`, omitting `TRANSFORMERS_INFERENCE_API`. If these two variables are set in e.g. `docker-compose.yml`, then dual encoding is used. Two separate containers should be specified. If  you want to use the current single encoding method, you can simply use the existing `TRANSFORMERS_INFERENCE_API`, and not use the two new variables.

```yml
version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:v1.10.1
    restart: on-failure:0
    ports:
     - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./data"
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_PASSAGE_INFERENCE_API: http://t2v-transformers-passage:8080/
      TRANSFORMERS_QUERY_INFERENCE_API: http://t2v-transformers-query:8080/
  t2v-transformers-passage:
    image: vblagoje/dpr-ctx_encoder-single-lfqa-wiki
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable
  t2v-transformers-query:
    image: vblagoje/dpr-question_encoder-single-lfqa-base
    environment:
      ENABLE_CUDA: 0 # set to 1 to enable
```

This implementation allows for example using @vblagoje's https://huggingface.co/vblagoje/dpr-ctx_encoder-single-lfqa-wiki and https://huggingface.co/vblagoje/dpr-question_encoder-single-lfqa-base. 

We can build a prototype to see if this works, take the learnings from there, then make a decision about extending the `text2vec-transformers` module vs building a new module. We need to learn how is the module loaded: is it compatible with the existing inference containers? If it needs new ones anyway, a separate module is probably easier, will allow for DPR specific config etc. Based on an evaluation we can decide to go with extending `text2vec-transformers` or making a new module.

Thanks to @vblagoje for the suggestion of supporting dual DPR encoders :)
