### ISSUE TITLE
Batch-Delete by Query

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#1915]
## Motivation / Desired State for Docs
---
*On [the `/v1/batch` page](https://weaviate.io/developers/weaviate/current/restful-api-references/batch.html#batch-data-objects) after "Batch data objects" and before "Batch references" add the following section:*

## Batch Delete By Query

*Note: This feature was introduced in `v1.13.0`*

You can use the `/v1/batch/objects` endpoint with the HTTP Verb `DELETE` to delete all objects that match a particular expression. To determine if an object is a match [a where-Filter is used](../graphql-references/filters.html#where-filter). The request body takes a single filter, but will delete all objects matched. It returns the number of matched objects as well as any potential errors. Note that there is a limit to how many objects can be deleted using this filter at once which is explained below.

### Maximum number of deletes per query

There is an upper limit to how many objects can be deleted using a single query. This protects against unexpected memory surges and very-long running requests which would be prone to client-side timeouts or network interruptions. If a filter matches many objects, only the first `n` elements are deleted. You can configure the amount `n` by setting `QUERY_MAXIMUM_RESULTS` in Weaviate's config. The default value is 10,000. Objects are deleted in the same order that they would be returned using the same filter in a a Get-Query. To delete more objects than the limit, run the same query multiple times, until no objects are matched anymore.

### Dry-Run before Deletion

You can use the dry-run option to see which objects would be deleted using your specified filter without deleting any objects yet. Depending on the verbosity set, you will either receive the total count of affected objects or a list of the affected IDs.

### Method and URL

```js
DELETE /v1/batch/objects
```

### Parameters

The body requires the following field:

| name | type | required | description |
| ---- | ---- | ---- | ---- |
| `match` | object | yes | an object outlining how to find the objects to be deleted, see an example below |
| `output` | string | no | optional, controls the verbosity of the output, see possible values below. Defaults to `"minimal"` |
| `dryRun` | bool | no | optional, if true, objects will not be deleted yet, but merely listed. Defaults to `false` |

#### A request body in detail

```yaml
{
  "match": {
    "class": "<ClassName>", # required
    "where": { /* where filter object */ },  # required
  },
  "output": "<output verbosity>" # Optional, one of "minimal", "verbose". Defaults to "minimal"
  "dryRun": <bool> # Optional, if true, objects will not be deleted yet, but merely listed. Defaults to "false"
}
```

Possible values for `output`

| value | effect |
| --- | --- |
| `minimal` | The result only includes counts. Information about objects is omitted if the deletes were successful. Only if an error occurred will the object be described. |
| `verbose` | The result lists all affected objects with their ID and deletion status, including both successful and unsuccessful deletes |

#### A response body in detail

```yaml
{
  "match": {
    "class": "<ClassName>",      # matches the request
    "where": { /* where filter object */ },  # matches the request
  },
  "output": "<output verbosity>" # matches the request
  "dryRun": <bool>
  "results": {
    "matches": "<int>"           # how many objects were matched by the filter
    "limit": "<int>"             # the most amount of objects that can be deleted in a single query, matches QUERY_MAXIMUM_RESULTS
    "successful": "<int>"        # how many objects were successfully deleted in this round
    "failed": "<int>"            # how many objects should have been deleted but could not be deleted
    "objects": [{                # one json object per weaviate object
      "id": "<id>",              # This successfully deleted object would be ommitted with output=minimal
      "status": "SUCCESS",       # Possible status values are: "SUCCESS", "FAILED", "DRYRUN"
      "error": null
    }, {
      "id": "<id>",              # This error'd object will always be listed, even with output=minimal
      "status": "FAILED",
      "errors": {
         "error": [{
             "message": "<error-string>"
         }]
      }
    ]}
  }
}
```

### Example request

*TODO: Add examples for all clients here*  

---

## Goals
* [x] A where filter can be specified and objects will be deleted if they match
* [x] The filter matches at most `QUERY_MAXIMUM_RESULTS` elements in a single request
* [x] When there are more matches than `QUERY_MAXIMUM_RESULTS`, the same request can be sent again until eventually all are deleted. (Consider adding a journey test with a low `QUERY_MAXIMUM_RESULTS` to verify this behavior)
* [x] The output verbosity can be controlled as outlined above
* [x] A dry-run flag can be set which will omit deletion, but still list the affected objects

### Effects outside of this repo
* [x] All clients are updated accordingly
* [x] The docs snippets are updated according to the above (do not merge until the release is live) including the client snippets. *Make sure that the heading level matches the docs, it may differ from this post. Some links in the snippets above need to be adjusted*.

## Tech Notes

* There is one place where we already use a `where` filter in the REST API which is in the `/v1/classifications` API, so the logic to parse a where filter should already exist
* Do not send `n` individual `adapters/repos/db/*DB.DeleteObjects` request. One deletion will affect multiple places with their own commit logs, including at least the object bucket and hnsw commit log, possibly more buckets for the inverted index. So if we were to individually delete 10,000 objects we'd have at least 20,000 `syscall.Write` which would be a major performance bottleneck. Instead build this similar to the existing `batch` methods which flush all the WALs just once at the very end. [Example of the grouped flushing](https://github.com/semi-technologies/weaviate/blob/0863bd30b0d285508ca441e3765b556b05bebd0c/adapters/repos/db/shard_write_batch_objects.go#L282-L300) which is called [here](https://github.com/semi-technologies/weaviate/blob/0863bd30b0d285508ca441e3765b556b05bebd0c/adapters/repos/db/shard_write_batch_objects.go#L62).
