### ISSUE TITLE
Proposal: Cross-Encoders as reranking

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#2111]
# Cross-Encoders as reranking

## WHAT
Reranking retrieved list of candidates from Weaviate based on cross-encoder model scores

## WHY
Because combining cross-encoders with bi-encoders can improve search results

## HOW
* Background information: 
  * https://www.sbert.net/examples/applications/retrieve_rerank/README.html
  * Experiment: https://github.com/semi-technologies/research/blob/main/cross-encoders/test-cross-encoder.ipynb
  * https://weaviate.io/blog/2022/08/Using-Cross-Encoders-as-reranker-in-multistage-vector-search.html
* Chaining cross-encoders as reranker behind the data retrieval step in Weaviate.
* Pretrained Cross-Encoders are available on HuggingFace: https://huggingface.co/cross-encoder. I'd advice to offer the following models out-of-the-box:
    * https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-12-v2 (highest quality on MS Marco, latest model)
    * https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2 (also highest quality on MS Marco, but faster)
* Custom models should also be possible, just like other Transformer Weaviate modules.
* There are multiple approaches for implementing this.
    1. Add this to the Weaviate setup in docker-compose file to add this to the pipeline, but *don't* offer settings in (GraphQL) querying. So the cross-encoder model will just be added in the background, and the user will not be able to tune this during query time. We can wait for the new Weaviate pipeline API design to offer tuning during queries. 
    2. Add this to Weaviate setup AND offer tuning in GraphQL queries. This offers more flexibility for the user, because they can play with the settings/parameters during query time, and vary parameters per query. This might come with some difficulties/confusion and perhaps breaking changes (in qna, see below) because the current GraphQL design is not suitable for making pipelines.
* The shown score in GraphQL results will be the final `score` (`certainty`), calculated with the (default) formula provided.

A search pipeline can look like this: 

![image](https://user-images.githubusercontent.com/26965746/184839750-4dd5eccb-5060-48bc-8d4b-46ec0ec28c2c.png)

### Usage - Setup
```yaml
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.14.1
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080' # <== First Phase / Stage
      CROSS_ENCODER_INFERENCE_API: 'http://ce-transformers:8080' # <== NEW - Second Phase / Stage
      QNA_INFERENCE_API: 'http://qna-transformers:8080' # READER
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-transformers'
      ENABLE_MODULES: 'text2vec-transformers,ce-transformers,qna-transformers'
      CLUSTER_HOSTNAME: 'node1'
      RETRIEVE_CANDIDATES_COUNT: 100 # <== NEW - How many initial candidates should be retrieved before reranking (in case query limit is smaller than 100)
      RERANKING_FORMULA: '0.5*t2v-transformers + 0.5*ce-transformers' # <== NEW - or MULTISTAGE_RANKING_FORMULA or EXPRESSION or SCORE_FORMULA
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
  ce-transformers: # <== NEW
    image: semitechnologies/cross-encoders:ms-marco-MiniLM-L-6-v2
    environment:
      ENABLE_CUDA: '0'
  qna-transformers:
    image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
    environment:
      ENABLE_CUDA: '0'
...
```

### Usage - GraphQL
Designing the GraphQL query to support this comes with some challenges. We are making a search pipeline here, which isn't supported in our current GraphQL design. The requirements:
* The `nearText` or `ask` results can be reranked by a cross encoder.
* You should be able to provide the ranking formula
* You should be able to define the number of candidates

The `certainty` is now the score given by the Cross-Encoder output or the formula if provided in the docker-compose. The `distance` remains how it is right now (the distance between the vector of the query and the result). The results should be sorted by default on descending `certainty`. 

```graphql
{
  Get {
    Paragraph (
      nearText: {
        concepts: ["high buildings in london"]
        rerank: {		
          crossEncoder: {
            active: true # true by default if this method is called, but this can be used to turn it off.
            number_of_candidates: 25 #candidate_count #default in env vars docker-compose
          }
          formula: "0.5*t2v-transformers + 0.5*ce-transformers" #default in env vars docker-compose
        }
      }
      limit: 3,
    ){
      content
      _additional { 
        certainty
      }
    }
  }
}
```

Alternatively:
* The ranking formula can be
  * `formula: "0.5*dense + 0.5*ce"`
  * `formula: [{dense: 0.5}, {ce: 0.5}]`

**With Q&A Module**
```graphql
{
  Get {
    Paragraph (
      limit: 1,
      ask: {
        question: "What is the tallest building in London?"        
        rerank: { <== this now requires a boolean value. So this would be a breaking change. 
          crossEncoder: {
            active: true # true by default if this method is called, but this can be used to turn it off.
            number_of_candidates: 25 #candidate_count #default in env vars docker-compose
          }
          qna: {
            active: true # true by default if this method is called, but this can be used to turn it off.
            number_of_candidates: 3 #candidate_count #default in env vars docker-compose
          }
          formula: "0.5*t2v-transformers + 0.25*ce-transformers + 0.25*qna-transformers" #default in env vars docker-compose
        }
      }
    ){
      content
      _additional { 
        certainty
        answer {
          result
        }
      }
    }
  }
}
```

#### Notes

The `rerank` argument inside the `ask` filter will be a breaking change with the proposed design. If we don't want this, we need to either 
1. Place the cross-encoders rerank outside the `ask` filter, or
2. Don't offer this setting with the qna module yet, and wait for new pipeline API designs.
