### ISSUE TITLE
Proposal: add sparse (bm25) indexing and search functionality

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#2133]
## WHAT
Search using sparse ranking functions like BM25 in Weaviate.

## WHY
Because a sparse method like BM25 performs well in keyword-based and out-of-domain search.

## HOW
* The BM25 score estimates the relevance of documents to a search query based on a probabilistic model.
* Add BM25 to GraphQL queries.
* This is a proposal for adding BM25 functionality that can be used without any modules attached, and thus can be used outside nearText search.
* The BM25 feature should be enabled in the docker-compose setup.
* The BM25 `score` is calculated using the [official Okapi BM25 formula](https://en.wikipedia.org/wiki/Okapi_BM25).
* Some preprocessing needs to be done to the query and documents:
  * tokenization, removing special characters, removing stopwords, normalization and stemming
* The score should be made positive, regardless if IDF returns a negative score.
* BM25 score is unbounded. Score normalization or scaling is not a good idea, because you loose information on how good the results are textually. However, when combining BM25 with Dense search, some form of normalization may be handy, so we can choose to offer normalization methods anyways. We can explain strategies in the documentation. Possible strategies are:
  * **minmax** - To leave the distribution intact, the best normalization method is a *minmax* approach, which takes the minimum BM25 score and maximum BM25 score into account. Taking the maximum BM25 score of a particular query as maximum in the formula is not a good idea, because then you're setting this result to the maximum score regardless the actual score. So a (theoretical) maximum needs to be defined, although bm25 is unbounded. This can be achieved by running a number of different queries, and recording the maximum value. Since this is quite complex to implement as feature, we can start by offering a setting with a default value, which the user can change on runtime. An example can be: `max((x/10), 1)` if the guessed maximum is 10.
  * **Arctangent** - An arctan scales values in a logarithmic manner. A function to scale scores <-1, 1> (practically between <0,1> because x will be a positive score) is: `2/pi*arctan(x)` (see https://www.mdpi.com/2227-7390/10/8/1335)

### Design - Weaviate setup
Requirements:
* Enable sparse indexing
* Choose which (one or more) space indexing method to enable (e.g. BM25, BM25F, TFIDF, etc). 
* Set parameters for BM25
  * b (between 0 and 1, default 0.75)
  * k1 (between 0 and infinite, usually between 0 and 3, default 1.2)
* Option to set a normalization function

**Schema**
The settings should be configured in the schema, per class:

```json
{
  "class": "string",                        
  "sparseIndexType": "bm25",                // NEW - can be used next to "vectorIndexType"
  "sparseIndexConfig": {                    // NEW - configuration of the sparse index
    "bm25": {
      "b": 0.75,
      "k1": 1.2
    }
  },
  "properties": [                            
    {
      "name": "string",                     
      "description": "string",              
      "dataType": [                         
        "string"
      ],
      "sparseIndexConfig": {                // NEW - overwrites the class specific config settings for this property           
        "bm25": {
          "b": 0.75,
          "k1": 1.2, 
        }
      },
      "indexInverted": true                 
    }
  ]
}
```

**Docker-compose**
In case we need to let Weaviate know on startup whether to enable sparse search, we can introduce an env var like `ENABLE_SPARSE_INDEX`: 

```yaml
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.14.1
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_SPARSE_INDEX: 'true' # <== NEW. Which method (e.g. bm25) can be specified in the schema. Not sure if this variable is needed in the docker-compose actually.
...
```

### Design - GraphQL Queries
```graphql
{
  Get {
    Paper (
      sparseSearch: {             # NEW - alternative name: sparse
       function: bm25,            # NEW - `bm25` is the first option to implement. This can be omitted if it is the same as specified in the schema. But if you want to use e.g. bm25+, then this can be specified here.
       query: "test",             
       properties: ["abstract"]   # NEW - if not specified, then take all properties into account,
       normalization: {           # NEW - optional, always scales between 0 and 1. Only 1 method can be chosen (minmax OR arctan)
          minmax: {
            active: true          # doesn't need this param, but introducing because otherwise not consistent with design..  
            max: 10,              # Optional - If not set, maximum is the maximum of that query.
            min: 0                # Optional - If not set, minumum is 0.
          }
          arctan: {               # doesn't need params, but introducing because otherwise not consistent with design..  
            active: true
          }
        }
      }
    ) {
      title
      abstract
      _additional {
        score                     # NEW - because distance is not a good word, it really is a ranking score instead of distance between vectors
      }
    }
  }
}
```

## Notes
* In the current experimental BM25 feature, the score returned is always negative. This can happen when IDF is negative which happens if the terms in the query appear in more than half of the documents in the dataset, but this is not the case with some queries in my experiments, so perhaps there is a mistake somewhere in the implemented formula.
* In the current experimental BM25 feature, no results are shown if the query contains capitals or special tokens. The query should be preprocessed properly in the final implementation.
