### ISSUE TITLE
Hybrid Search (combining Vector + Sparse search)

### ISSUE THREAD

**Issue by laura-ham** [semi-technologies/weaviate#2134]
## WHAT
Combining vector search with sparse (e.g. BM25) search in one query

## WHY
To bridge the gap between sparse search and vector search.

### Longer why
Vector search (using dense vectors, computed by ML models) works well in-domain, but has poor performance out-of-domain.
BM25 search works well out-of-domain, because it uses sparse methods (keyword matching), but can't perform context-based search.
Combining both methods will improve search results out-of-domain.

## HOW
* This issue and implementation depend on issue https://github.com/semi-technologies/weaviate/issues/2133
* Do both a dense and BM25 search using a query (in parallel)
* You should be able to define a function to combine the results into 1 result list, using the scores of data in both candidate lists.
* A default function can be defined in the Weaviate setup, but can be overwritten in the GraphQL query.
* BM25 score is unbounded. Score normalization or scaling is not a good idea, because you lose information on how good the results are textually. However, when combining BM25 with Dense search, some form of normalization may be handy, so we can choose to offer normalization methods anyways. We can explain strategies in the documentation. Possible strategies are:
  * **minmax** - To leave the distribution intact, the best normalization method is a *minmax* approach, which takes the minimum BM25 score and maximum BM25 score into account. Taking the maximum BM25 score of a particular query as maximum in the formula is not a good idea, because then you're setting this result to the maximum score regardless of the actual score. So a (theoretical) maximum needs to be defined, although BM25 is unbounded. This can be achieved by running a number of different queries, and recording the maximum value. Since this is quite complex to implement as a feature, we can start by offering a setting with a default value, which the user can change at runtime. An example can be: `max((x/10), 1)` if the guessed maximum is 10.
  * **Arctangent** - An arctan scales values in a logarithmic manner. A function to scale scores <-1, 1> (practically between <0,1> because x will be a positive score) is: `2/pi*arctan(x)` (see https://www.mdpi.com/2227-7390/10/8/1335)

### Design - Weaviate setup
Requirements:
* Dense retrieval and sparse retrieval independently (with the same or different query)
* Combine the result of both methods using a scoring function

**Schema**
The settings should be configured in the schema, per class:

```json
{
  "class": "string",
  "vectorIndexType": "hnsw",                
  "vectorIndexConfig": {
    ...                                     
  },
  "vectorizer": "text2vec-transformers",
  "moduleConfig": {
    "text2vec-transformers": {  
      "vectorizeClassName": true            
    }
  },                       
  "sparseIndexType": "bm25",                
  "sparseIndexConfig": {                   
    "bm25": {
      "b": 0.75,
      "k1": 1.2
    }
  },
  "properties": [                            
    {
      "name": "string",                     
      "description": "string",              
      "dataType": [                         
        "string"
      ],
      "sparseIndexConfig": {                
        "bm25": {
          "b": 0.75,
          "k1": 1.2, 
        }
      },
      "indexInverted": true                 
    }
  ]
}
```

**Docker-compose**
In case we need to let Weaviate know on startup whether to enable sparse search, we can introduce an env var like `ENABLE_SPARSE_INDEX`: 

```yaml
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.14.1
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_SPARSE_INDEX: 'true' # <== NEW. Which method (e.g. bm25) can be specified in the schema. Not sure if this variable is needed in the docker-compose actually.
    t2v-transformers:
      image: semitechnologies/transformers-inference:sentence-transformers-msmarco-distilroberta-base-v2
      environment:
        ENABLE_CUDA: 0 # set to 1 to enable
...
```

### Design - GraphQL Queries
The current API is documented in [this comment](https://github.com/semi-technologies/weaviate/issues/2134#issuecomment-1323955096).

Below is the more elaborate original proposal.

```graphql
{
  Get {
    Paper (
      hybridSearch: {               # NEW
        operands: [{
          sparseSearch: {           # inherits all fields from sparseSearch. alternative name: sparse
            function: bm25,
            query: "my query",
            properties: ["abstract"],
            normalization: {
              minmax: {
                max: 10
              }
            }
          },
          weight: 0.2
        }, {
          nearText: {               # inherits all fields from nearText. alternative name: dense or denseSearch
            concepts: ["my query"],
            certainty: 0.7   
          },
          weight: 0.8
        }],
        type: Sum                   # or Average, or RRF (with RRF, weights will be discarded)
      }
    ) {
      title
      abstract
      _additional {
        score    # NEW - because distance is not a good word, it really is a ranking score instead of distance between vectors
      }
    }
  }
}
```

Multiple sparse searches should also be supported, like: 

```graphql
{
  Get {
    Paper (
      hybridSearch: {               # NEW
        operands: [{
          sparseSearch: {           # inherits all fields from sparseSearch. alternative name: sparse
            function: bm25,
            query: "my query",
            properties: ["abstract"],
            normalization: {
              minmax: {
                max: 10
              }
            }
          },
          weight: 0.2
        }, {
          sparseSearch: {           # inherits all fields from sparseSearch. alternative name: sparse
            function: bm25,
            query: "my query 2",
            properties: ["title"],
            normalization: {
              minmax: {
                max: 10
              }
            },
            limit: 100
          },
          weight: 0.2
        }, {
          nearText: {              # inherits all fields from nearText. alternative name: dense or denseSearch
            concepts: ["my query"],
            certainty: 0.7,
            limit: 100   
          },
          weight: 0.6
        }],
        type: Sum                  # or Average, or RRF (with RRF, weights will be discarded)
      }
    ) {
      title
      abstract
      _additional {
        score        # NEW - because distance is not a good word, it really is a ranking score instead of distance between vectors
      }
    }
  }
}
```
