### ISSUE TITLE
Nodes endpoint

### ISSUE THREAD

**Issue by trengrj** [semi-technologies/weaviate#2145]
Provide a list of healthy / connected nodes in cluster and some summary metrics at a node lever including ideally:

1. Total count of shards per node
2. Total count of vectors per node
3. Weaviate versions / git commit per node
4. CPU / Disk / Memory usage per node (not mandatory but nice to have)

**Comment by etiennedi** [comment]
Thanks, this should be easy to do and it's already on the list for v1.16. Some comments and questions:

1. clear, should be easy to do
2. would the number of objects (regardless of whether they have a vector or not) also work? The reason for this is that that's much easier and computationally cheaper to obtain.
3. Great idea, I think we're currently not including the git commit at compile time, but that should be easy to do
4. Disk should be easy, the other two may be more difficult. Let's see what we can obtain easily

**Comment by trengrj** [comment]
👍 Number of objects actually makes more sense especially if it is cheaper to obtain.

**Comment by etiennedi** [comment]
An API proposal for the above:

```http
GET /v1/nodes
```
returns
```yaml
{
  "nodes": [
    {
      "name": "weaviate-7",
      "version": "1.16-alpha.0",
      "gitHash": "8cd2ef",
      "stats": {
        "shardCount":3
        "objectCount": 73328,
        # TODO: If possible add stats about disk/mem/etc here
      },
      "shards": [
        {
          "name":"azuawSAd9312F",
          "class": "Class_7",
          "objectCount": 13328,
        }, {
          "name":"cupazAaASdfPP",
          "class": "Foo",
          "objectCount": 10000,
        }, {
          "name":"FE8sfs399DJAjaw",
          "class": "Bar",
          "objectCount": 50000,
        },
      ],
    },
    # ... other nodes here
   ] 
}
```
