### ISSUE TITLE
Backups API Proposal after Stakeholder session

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#2147]
*Note: This proposal was declined in favor of Proposal 2 which is in a comment below*

This is the updated API proposal from the Stakeholder session on August 29 based on the feedback from in-company stakeholders and community users.

### Main Ideas
* A backup is a high-level resource that includes classes, it is no longer a sub-resource of an existing schema class
* The most common usecase is to backup everything, but there should be options to only include specific classes or exclude some classes
* A new endpoint is added to list existing backups

## Create a backup

```yaml
POST /v1/backups/
{
  "id": "my_backup_id",
  "storageProvider": "gcs",
  "config": {} # <----- not supported in first iteration, but in the future we want to be able to override specific config
  "include": ["ClassA", "ClassB"] # if not set all classes are included
  "exclude": ["ClassC", "ClassD"] # only one of include or exclude can be set
}
```

## Check the status of an ongoing backup
```yaml
GET /v1/backups/my_backup_id
```

TODO: Storage Provider???

## Restore a backup
You can limit the amount of classes you want to restore if you only want to access a specific class - even if the snapshot contains more classes.
```yaml
POST /v1/backups/restore
{
  "id": "my_backup_id",
  "config": {} # <----- not supported in first iteration, but in the future we want to be able to override specific config
  "include": ["ClassA", "ClassB"] # if not set all classes are included
  "exclude": ["ClassC", "ClassD"] # only one of include or exclude can be set
}
```

## Get status of an ongoing restoration
```yaml
GET /v1/backups/restore/my_backup_id
```

**Comment by etiennedi** [comment]
## Alternative Propsoal ("Proposal 2")

Everything is identical to the above proposal, except that the storage provider is moved back into the URL. This means we can keep the stateless nature of backups (all state resides on the storage provider):

```yaml
POST /v1/backups/gcs/
{
  "id": "my_backup_id",
  "config": {} # <----- not supported in first iteration, but in the future we want to be able to override specific config
  "include": ["ClassA", "ClassB"] # if not set all classes are included
  "exclude": ["ClassC", "ClassD"] # only one of include or exclude can be set
}
```

```yaml
GET /v1/backups/gcs/my_backup_id # get the status of ongoing backup
```

```
POST /v1/backups/gcs/restore # restore a backup
{
  "id": "my_backup_id",
  "config": {} # <----- not supported in first iteration, but in the future we want to be able to override specific config
  "include": ["ClassA", "ClassB"] # if not set all classes are included
  "exclude": ["ClassC", "ClassD"] # only one of include or exclude can be set
}
```

```
GET /v1/backups/gcs/restore/my_backup_id # get the status of ongoing restoration
```
