### ISSUE TITLE
Add property to shard "DCDU9S6IYsV7": store is read-only

### ISSUE THREAD

**Issue by eostis** [semi-technologies/weaviate#2348]
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1785759/201056027-918beabe-0425-4400-acb8-74e35f20a33b.png">

Hi,

Version: latest

I get this error while indexing, but only within github actions.

When I execute the same configuration locally, the error vanishes.

docker file:
`FROM semitechnologies/weaviate:latest
`

docker compose file:
```
version: '3.4'

services:
  weaviate:
    container_name: weaviate # hostname in WPSOLR config
    image: ${WPSOLR_IMAGE_NAME}:weaviate
    networks:
      - default
      - wpsolr-external-network-created-with-docker-network-create
    ports:
      - 8865:8080
    environment:
      AUTOSCHEMA_ENABLED: 'false' # Important to add custom WPSOLR data types
      QUERY_DEFAULTS_LIMIT: 20

      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      #AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      #AUTHENTICATION_OIDC_ENABLED: 'true'
      #AUTHENTICATION_OIDC_ISSUER: 'https://wpsolr.eu.auth0.com/'
      #AUTHENTICATION_OIDC_USERNAME_CLAIM: 'email'
      #AUTHENTICATION_OIDC_GROUPS_CLAIM: 'groups'
      #AUTHENTICATION_OIDC_CLIENT_ID: 'https://wpsolr.eu.auth0.com/api/v2/'
      #AUTHORIZATION_ADMINLIST_ENABLED: 'true'
      #AUTHORIZATION_ADMINLIST_USERS: 'john@doe.com'

      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLIP_INFERENCE_API: 'http://multi2vec-clip:8080'
      TRANSFORMERS_INFERENCE_API: 'http://t2v-transformers:8080'
      QNA_INFERENCE_API: 'http://qna-transformers:8080'
      ENABLE_MODULES: 'text2vec-huggingface,text2vec-openai,multi2vec-clip,text2vec-transformers,qna-transformers'
      CLUSTER_HOSTNAME: 'node1'

  multi2vec-clip:
    image: semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32-multilingual-v1
    environment:
      ENABLE_CUDA: '0'
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-msmarco-distilbert-base-v2
    environment:
      ENABLE_CUDA: '0'
  qna-transformers:
    image: semitechnologies/qna-transformers:bert-large-uncased-whole-word-masking-finetuned-squad
    environment:
      ENABLE_CUDA: '0'

```
