### ISSUE TITLE
FR: Support arbitrary amount of vector indexes on object

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#2465]
Right now an object is associated with 0..1 vectors. But for some use cases it would be nice to have multiple vector properties. For example, we could introduce the `dataType` `vector` and then users could add arbitrary vectors, such as:

```yaml:
properties:
-  name: title
    dateType: ['text']
-  name title_vector
    dataType: ['vector']
```

Note: It would probably make sense to name the type after the vector data type, e.g. instead of just having `vector`, we could have specific vectors, such as `vectorFloat32`, `vectorFloat16`, `vectorInt8`, `vectorBinary`, etc.
