### ISSUE TITLE
Query with multiple operands and cross-references returns incomplete result

### ISSUE THREAD

**Issue by jbed94** [semi-technologies/weaviate#2537]
There is a problem when calling queries consisting of multiple operands containing cross-references. Using standard queries, like:
```
{
  Get{
    Content(where:{
      operator: And
      operands: [{
        path: ["cited_by_count"]
        operator: GreaterThan
        valueInt: 9999
      },{
        path: ["cited_by_count"]
        operator: LessThan
        valueInt: 10001
      }]
    }){
      name
      cited_by_count
    }
  }
}
```
The search engine will first filter the entire inverted index to find all records with property `cited_by_count > 9999`, then will filter the whole inverted index to find all records with property `cited_by_count < 10001`, and finally, will combine two intermediate results into a single result list containing one record. Here, it's important to mention, that only final results will be limited to an environment variable `QUERY_MAXIMUM_RESULTS` which by default is set to 10000.

I suspect that there are some optimizations in a simple query like the second operand is applied to intermediate results already, but it seems not relevant for now (?).

However, if you query Content class with cross-references, e.g.:
```
{
  Get{
    Representation(where:{
      operator: And
      operands: [{
        path: ["reference", "Content", "cited_by_count"]
        operator: GreaterThan
        valueInt: 9999
      },{
        path: ["reference", "Content", "cited_by_count"]
        operator: LessThan
        valueInt: 10001
      }]
    }){
      name
      reference{
        ... on Content{
          cited_by_count
        }
      }
    }
  }
}
```
the query will be split into **sub-queries**:
- records of Representation class with references to Content class with a property `cited_by_count > 9999`,
- records of Representation class with references to Content class with a property `cited_by_count < 10001`,
and only after receiving the results of sub-queries, the aggregation will take place.

But! Since the above query is split into sub-queries and each query returns at most `QUERY_MAXIMUM_RESULTS` results, the first sub-query will return results with `cited_by_count` starting from value 10000 (since the inverted index is sorted (???)) and the second query will return results with `cited_by_count` starting from 0. If there are more than 10000 records with property `cited_by_count < 10000` (10001 - 1), the second query will be trimmed into `QUERY_MAXIMUM_RESULTS` size, **thus removing the common records for both sub-queries (since results are first sorted (???))**.

[I attach a gist for reproducing an issue and my \"explanation\".](https://gist.github.com/jbed94/eb4cbe0c943b93c2231928c47638ae32)

I use a default docker-compose file for tests:
```
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.17.0
    ports:
    - 8080:8080
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: ''
      CLUSTER_HOSTNAME: 'node1'
```

Could you please check if the above is true? And if so, Is there a way (better than increasing `QUERY_MAXIMUM_RESULTS`) to always get full results when using cross-reference operands? 

Thanks!
