### ISSUE TITLE
Pluggable Auth: Minimal RBAC Authorization

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#802]
as outlined in #628

**Comment by etiennedi** [comment]
# Design Proposal

### Goals
* Maximum Flexibility with minimal effort for common cases
* No one one has any permissions by default, all permissions need to be explicitly given
* Asterisk (`*`) can be used to mean "all resources of this category"
* Modelled after Kubernetes RBAC, because the user experience is great and users might already be familiar with the system

## 2-Step Configuration

We have two resources to configure Authorization:
* A `Role` grants permissions to everyone who owns the role, for example ("get all things")
* A `RoleBinding` assigns a role to a a user or group

### Role
```yaml
name: string
rules:
  - kinds: []string
    classes: []string
    verbs: []string
```

### RoleBinding
```yaml
name: string
roleName: string
subjects:
  - type: one of 'user', 'group'
     name: string
```

### Exmaple configs

#### Example 1: Anonymous reads, but writing restricted
Goal: Anonymous users can read everything, admins can create/update/delete everything

##### Roles
```yaml
name: read-all
rules:
  - kinds: ["*"]
    classes: ["*"]
    verbs: ["GET"]
```
```yaml
name: crud-all
rules:
  - kinds: ["*"]
    classes: ["*"]
    verbs: ["*"]
```

##### Role-Bindings:
```yaml
name: anonymous-read-all
roleName: read-all
subjects:
  - type: group
     name: anonymous
```
```yaml
name: admin-crud-all
roleName: crud-all
subjects:
  - type: group
     name: admin
```

#### Example 2: Fruit Salad
This example shows that we have maximum flexibility, even this overly complex use-case would easily be possible:

Goal: 
- Anyone can read all Actions
- Bob can read Bananas and read Apples
- Remi can CRUD Oranges and read Bananas and Oranges
- Micha can CRUD all actions 

##### Roles
```yaml
name: read-actions
rules:
  - kinds: ["action"]
    classes: ["*"]
    verbs: ["GET"]
```
```yaml
name: banana-apple-read
rules:
  - kinds: ["thing"]
    classes: ["apple", "banana"]
    verbs: ["GET"]
```
```yaml
name: orange-crud
rules:
  - kinds: ["thing"]
    classes: ["orange"]
    verbs: ["*"]
```
```yaml
name: actions-crud
rules:
  - kinds: ["action"]
    classes: ["*"]
    verbs: ["*"]
```

##### Role-Bindings:
```yaml
name: anonymous-read-actions
roleName: read-all
subjects:
  - type: group
     name: anonymous
```
```yaml
name: banana-apple-readers
roleName: banana-apple-read
subjects:
  - type: user
     name: bob@semi.technology
  - type: user
     name: remi@semi.technology
```
```yaml
name: orange-cruder
roleName: orange-crud
subjects:
  - type: user
     name: remi@semi.technology
```
```yaml
name: actions-cruder
roleName: actions-crud
subjects:
  - type: user
     name: micha@semi.technology
```

## Feedback

@bobvanluijt @studiospindle Happy to hear your feedback on this RBAC Authorization proposal :)
