### ISSUE TITLE
Document config changes introduced with Analytics Engine

### ISSUE THREAD

**Issue by etiennedi** [semi-technologies/weaviate#810]
Please also see this draft I made, I don't know if it's up-to-date anymore. Please validate, but maybe you can use some parts of it:

```yaml
name: myConfigWithJanusgraphAndSpark
analyticsEngine:
  # enabled configures whether an analytics engine should be used. 
  # Setting this to true leads to the options "useAnalyticsEngine" and
  # "forceRecalculate" to become available in the GraphQL GetMeta->Kind->Class
  # and Aggregate->Kind->Class.
  #
  # Important: If enabled is set to true, you must also configure an
  # analytics engine in your database connector. If the chosen connector
  # does not support an external analytics engine, enabled must be set
  # to false.
  enabled: true  
  
  # defaultUseAnalyticsEngine configures what the "useAnalyticsEngine"
  # in the GraphQL API will default to when not set.
  defaultUseAnalyticsEngine: true 
database:
  name: janusgraph
  database_config:  
    url: http://janus:8182
    analyticsEngine:
      # enabled configures whether an analytics engine for this particular connector
      # is used.
      # Important: If enabled is set to true, the overall configuration property
      # analyticsEngine.enabled must also be set to true. 
      enabled: true

      # type configures which analytics engine is used with this connector
      # currently the janusgraph connector supports only 'spark-analytics-api'
      type: spark-analytics-api

      # url to discover the specific analytics backend
      url: http://analytics-api:8080
```
